
package webservices2015.pharmacy.clinical.epic;

import javax.xml.ws.WebFault;
import com.epicsystems.interconnect_2004_05.FaultType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "ApplicationFault", targetNamespace = "urn:epicsystems.com:Interconnect.2004-05.Faults")
public class IPharmacyServices2015GetPrescriptionInfoApplicationFaultFaultMessage
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultType faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IPharmacyServices2015GetPrescriptionInfoApplicationFaultFaultMessage(String message, FaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IPharmacyServices2015GetPrescriptionInfoApplicationFaultFaultMessage(String message, FaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.epicsystems.interconnect_2004_05.FaultType
     */
    public FaultType getFaultInfo() {
        return faultInfo;
    }

}
